name: Automerge Codex PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: |
      github.event.pull_request.user.login == 'cdomotor' &&
      contains(github.event.pull_request.title, 'codex')
    runs-on: ubuntu-latest
    steps:
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: squash
